name: digit41
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.3.8
  bip39: ^1.0.6
  bip32: ^2.0.0
  web3dart: ^2.1.4
  dio: ^4.0.0
  pointycastle: ^3.2.0-rc0
  clipboard: ^0.1.3
  barcode_scan2: ^4.1.4
  hive: ^2.0.4
  responsive_framework: ^0.1.4
  path_provider: ^2.0.2
  permission_handler: ^8.1.3
  url_launcher: ^6.0.6
  shared_preferences: ^2.0.6
  passcode_screen: ^2.0.0
  local_auth: ^1.1.6
  firebase_messaging: ^10.0.4
#  firebase_core: ^1.3.0
  flutter_local_notifications: ^8.1.1
  flutter_statusbarcolor_ns: ^0.3.0-nullsafety
  cached_network_image: ^3.1.0

#  flutter_launcher_icons: ^0.9.1
#flutter_icons:
#  image_path_android: "assets/images/app_icon.jpg"
#
#  image_path_ios: "assets/images/app_icon.jpg"
#
#  android: true # can specify file name here e.g. "ic_launcher"
#
#  ios: true # can specify file name here e.g. "My-Launcher-Icon"


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/


  fonts:
   - family: IBM_Plex
     fonts:
       - asset: assets/fonts/ibm_plex_sans_bold.ttf
       - asset: assets/fonts/ibm_plex_sans_light.ttf
       - asset: assets/fonts/ibm_plex_sans_medium.ttf
       - asset: assets/fonts/ibm_plex_sans_regular.ttf
       - asset: assets/fonts/ibm_plex_sans_thin.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
